[build]
  command = "npm run build || echo 'no build'"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/telegram-webhook"
  to = "/.netlify/functions/telegram-webhook"
  status = 200

[[redirects]]
  from = "/api/cryptobot-webhook"
  to = "/.netlify/functions/cryptobot-webhook"
  status = 200


